version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
      - ENV=development
      - PORT=5000
   
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mysql
