version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
      - ENV=development
      - PORT=5000
   
  postgres:
    image: postgres:latest
    restart: always
    container_name: ppostgres_db
    ports:
      - "5432:5432"
    volumes:
      - data:/home/andrew/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db

volumes:
  data:
    external: true
